In [48]:
import pandas as pd
import polars as pl
import yaml

In [49]:
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [50]:
widef_pl = pl.read_csv(r"C:\Users\Beatriz Fernandes\Desktop\IronHack\Week by Week\W4\first_project\data\raw\WB_WDI_WIDEF.csv")
widef_pl.head()

shape: (5, 106)
┌───────────────┬───────────────┬────────┬──────┬───┬───────────┬───────────┬───────────┬──────────┐
│ STRUCTURE     ┆ STRUCTURE_ID  ┆ ACTION ┆ FREQ ┆ … ┆ 2021      ┆ 2022      ┆ 2023      ┆ 2024     │
│ ---           ┆ ---           ┆ ---    ┆ ---  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str           ┆ str           ┆ str    ┆ str  ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════════╪═══════════════╪════════╪══════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 11.751292 ┆ 11.754866 ┆ 11.737018 ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 1.2619e10 ┆ 1.2799e10 ┆ 1.1877e10 ┆ 8.7202e9 │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 2274.0    ┆ 2274.0    ┆ null      ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 13.89779  ┆ 7.898441  ┆ 0.401935  ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 2.7884e10 ┆ 2.9520e10 ┆ 2.9526e10 ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
└───────────────┴───────────────┴────────┴──────┴───┴───────────┴───────────┴───────────┴──────────┘

In [51]:
hci_pl = pl.read_csv(r"C:\Users\Beatriz Fernandes\Desktop\IronHack\Week by Week\W4\first_project\data\raw\WB_HCI_WIDEF.csv")
hci_pl.head()

shape: (5, 17)
┌──────┬────────────┬──────────┬───────────────┬───┬──────────────┬──────────┬──────────┬──────────┐
│ FREQ ┆ FREQ_LABEL ┆ REF_AREA ┆ REF_AREA_LABE ┆ … ┆ UNIT_MULT_LA ┆ 2010     ┆ 2018     ┆ 2020     │
│ ---  ┆ ---        ┆ ---      ┆ L             ┆   ┆ BEL          ┆ ---      ┆ ---      ┆ ---      │
│ str  ┆ str        ┆ str      ┆ ---           ┆   ┆ ---          ┆ f64      ┆ f64      ┆ f64      │
│      ┆            ┆          ┆ str           ┆   ┆ str          ┆          ┆          ┆          │
╞══════╪════════════╪══════════╪═══════════════╪═══╪══════════════╪══════════╪══════════╪══════════╡
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan   ┆ … ┆ Units        ┆ 0.771392 ┆ 0.803774 ┆ 0.811161 │
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan   ┆ … ┆ Units        ┆ 0.7252   ┆ 0.758776 ┆ 0.766116 │
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan   ┆ … ┆ Units        ┆ 0.747581 ┆ 0.780382 ┆ 0.787741 │
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan   ┆ … ┆ Units        ┆ null     ┆ 6.795722 ┆ 6.915841 │
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan   ┆ … ┆ Units        ┆ null     ┆ 9.544137 ┆ 9.655388 │
└──────┴────────────┴──────────┴───────────────┴───┴──────────────┴──────────┴──────────┴──────────┘

In [52]:
hcp_pl = pl.read_csv(r"C:\Users\Beatriz Fernandes\Desktop\IronHack\Week by Week\W4\first_project\data\raw\WB_HCP_EMP_2WAP_A_WIDEF.csv")
hcp_pl.head()

shape: (5, 55)
┌──────┬────────────┬──────────┬────────────────┬───┬────────┬────────┬────────┬────────┐
│ FREQ ┆ FREQ_LABEL ┆ REF_AREA ┆ REF_AREA_LABEL ┆ … ┆ 2021   ┆ 2022   ┆ 2023   ┆ 2024   │
│ ---  ┆ ---        ┆ ---      ┆ ---            ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str  ┆ str        ┆ str      ┆ str            ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64    │
╞══════╪════════════╪══════════╪════════════════╪═══╪════════╪════════╪════════╪════════╡
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan    ┆ … ┆ 14.652 ┆ 4.528  ┆ 4.514  ┆ 4.475  │
│ A    ┆ Annual     ┆ AFG      ┆ Afghanistan    ┆ … ┆ 45.587 ┆ 36.823 ┆ 36.797 ┆ 36.66  │
│ A    ┆ Annual     ┆ AGO      ┆ Angola         ┆ … ┆ 85.145 ┆ 83.702 ┆ 83.669 ┆ 83.786 │
│ A    ┆ Annual     ┆ AGO      ┆ Angola         ┆ … ┆ 87.513 ┆ 87.507 ┆ 87.574 ┆ 87.737 │
│ A    ┆ Annual     ┆ ALB      ┆ Albania        ┆ … ┆ 56.587 ┆ 57.981 ┆ 57.824 ┆ 57.984 │
└──────┴────────────┴──────────┴────────────────┴───┴────────┴────────┴────────┴────────┘

In [53]:
widef_pl = widef_pl.select([
    'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL',
    '2010', '2018'
])

widef_pl.head()

shape: (5, 8)
┌──────────┬────────────┬────────────┬────────────┬───────────┬────────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_L ┆ INDICATOR  ┆ INDICATOR_ ┆ SEX_LABEL ┆ AGE_LABEL  ┆ 2010      ┆ 2018      │
│ ---      ┆ ABEL       ┆ ---        ┆ LABEL      ┆ ---       ┆ ---        ┆ ---       ┆ ---       │
│ str      ┆ ---        ┆ str        ┆ ---        ┆ str       ┆ str        ┆ f64       ┆ f64       │
│          ┆ str        ┆            ┆ str        ┆           ┆            ┆           ┆           │
╞══════════╪════════════╪════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ MDA      ┆ Moldova    ┆ WB_WDI_AG_ ┆ Forest     ┆ Total     ┆ All age    ┆ 11.400304 ┆ 11.752972 │
│          ┆            ┆ LND_FRST_Z ┆ area (% of ┆           ┆ ranges or  ┆           ┆           │
│          ┆            ┆ S          ┆ land area) ┆           ┆ no         ┆           ┆           │
│          ┆            ┆            ┆            ┆           ┆ breakdown… ┆           ┆           │
│ PSE      ┆ West Bank  ┆ WB_WDI_NY_ ┆ Gross      ┆ Total     ┆ All age    ┆ 9.4635e9  ┆ 1.3318e10 │
│          ┆ and Gaza   ┆ GDP_FCST_K ┆ value      ┆           ┆ ranges or  ┆           ┆           │
│          ┆            ┆ D          ┆ added at   ┆           ┆ no         ┆           ┆           │
│          ┆            ┆            ┆ basic pri… ┆           ┆ breakdown… ┆           ┆           │
│ ECU      ┆ Ecuador    ┆ WB_WDI_AG_ ┆ Average    ┆ Total     ┆ All age    ┆ 2274.0    ┆ 2274.0    │
│          ┆            ┆ LND_PRCP_M ┆ precipitat ┆           ┆ ranges or  ┆           ┆           │
│          ┆            ┆ M          ┆ ion in     ┆           ┆ no         ┆           ┆           │
│          ┆            ┆            ┆ depth…     ┆           ┆ breakdown… ┆           ┆           │
│ SMR      ┆ San Marino ┆ WB_WDI_NY_ ┆ GDP growth ┆ Total     ┆ All age    ┆ -5.473684 ┆ 1.493905  │
│          ┆            ┆ GDP_MKTP_K ┆ (annual %) ┆           ┆ ranges or  ┆           ┆           │
│          ┆            ┆ D_ZG       ┆            ┆           ┆ no         ┆           ┆           │
│          ┆            ┆            ┆            ┆           ┆ breakdown… ┆           ┆           │
│ NZL      ┆ New        ┆ WB_WDI_NY_ ┆ Taxes less ┆ Total     ┆ All age    ┆ 1.9830e10 ┆ 2.6453e10 │
│          ┆ Zealand    ┆ TAX_NIND_K ┆ subsidies  ┆           ┆ ranges or  ┆           ┆           │
│          ┆            ┆ N          ┆ on produc… ┆           ┆ no         ┆           ┆           │
│          ┆            ┆            ┆            ┆           ┆ breakdown… ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴───────────┴────────────┴───────────┴───────────┘

In [54]:
widef_pl["SEX_LABEL"].unique()

shape: (3,)
Series: 'SEX_LABEL' [str]
[
	"Total"
	"Female"
	"Male"
]

In [55]:
widef_pl["AGE_LABEL"].unique()

shape: (22,)
Series: 'AGE_LABEL' [str]
[
	"15 to 24 years old"
	"70 to 74 years old"
	"All age ranges or no breakdown…
	"10 to 14 years old"
	"under 15 years old"
	…
	"45 to 49 years old"
	"75 to 79 years old"
	"65 to 69 years old"
	"5 to 9 years old"
	"50 to 54 years old"
]

In [56]:
import numpy as np
import polars as pl

working_age = [
    "WB_WDI_SP_POP_2024",
    "WB_WDI_SP_POP_2529",
    "WB_WDI_SP_POP_3034",
    "WB_WDI_SP_POP_3539",
    "WB_WDI_SP_POP_4044",
    "WB_WDI_SP_POP_4549",
    "WB_WDI_SP_POP_5054",
    "WB_WDI_SP_POP_5559",
    "WB_WDI_SP_POP_6064"
]

retirement_age = [
    "WB_WDI_SP_POP_65UP",
    "WB_WDI_SP_POP_6569",
    "WB_WDI_SP_POP_7074",
    "WB_WDI_SP_POP_7579",
    "WB_WDI_SP_POP_80UP"
]

widef_pl = widef_pl.with_columns(
    pl.when(pl.col("INDICATOR").str.contains("SP_POP_2024|SP_POP_2529|SP_POP_3034|SP_POP_3539|SP_POP_4044|SP_POP_4549|SP_POP_5054|SP_POP_5559|SP_POP_6064"))
    .then(pl.lit("working_age"))
    .when(pl.col("INDICATOR").str.contains("SP_POP_65UP|SP_POP_6569|SP_POP_7074|SP_POP_7579|SP_POP_80UP"))
    .then(pl.lit("retirement_age"))
    .otherwise(pl.lit("other"))
    .alias("AGE_GROUP")
)

print(widef_pl.filter(pl.col("AGE_GROUP") == "working_age"))
print(widef_pl.filter(pl.col("AGE_GROUP") == "retirement_age"))

shape: (4_770, 9)
┌──────────┬────────────┬────────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ REF_AREA ┆ REF_AREA_L ┆ INDICATOR  ┆ INDICATOR ┆ … ┆ AGE_LABEL ┆ 2010     ┆ 2018     ┆ AGE_GROUP │
│ ---      ┆ ABEL       ┆ ---        ┆ _LABEL    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---       │
│ str      ┆ ---        ┆ str        ┆ ---       ┆   ┆ str       ┆ f64      ┆ f64      ┆ str       │
│          ┆ str        ┆            ┆ str       ┆   ┆           ┆          ┆          ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ FRO      ┆ Faroe      ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 25 to 29  ┆ 4.619012 ┆ 5.397687 ┆ working_a │
│          ┆ Islands    ┆ POP_2529_F ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ E_5Y       ┆ 25-29,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ female …  ┆   ┆           ┆          ┆          ┆           │
│ LTU      ┆ Lithuania  ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.999132 ┆ 7.448568 ┆ working_a │
│          ┆            ┆ POP_4549_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 45-49,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ BEL      ┆ Belgium    ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 50 to 54  ┆ 7.232739 ┆ 7.256239 ┆ working_a │
│          ┆            ┆ POP_5054_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 50-54,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ BIH      ┆ Bosnia and ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.431352 ┆ 6.273706 ┆ working_a │
│          ┆ Herzegovin ┆ POP_4549_F ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆ a          ┆ E_5Y       ┆ 45-49,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ female …  ┆   ┆           ┆          ┆          ┆           │
│ IND      ┆ India      ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 60 to 64  ┆ 2.510203 ┆ 3.275494 ┆ working_a │
│          ┆            ┆ POP_6064_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 60-64,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ FCS      ┆ Fragile    ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 30 to 34  ┆ 6.533288 ┆ 6.566336 ┆ working_a │
│          ┆ and        ┆ POP_3034_F ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆ conflict   ┆ E_5Y       ┆ 30-34,    ┆   ┆           ┆          ┆          ┆           │
│          ┆ affected … ┆            ┆ female …  ┆   ┆           ┆          ┆          ┆           │
│ SAS      ┆ South Asia ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 20 to 24  ┆ 9.451445 ┆ 9.251169 ┆ working_a │
│          ┆            ┆ POP_2024_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 20-24,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ HIC      ┆ High       ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.410345 ┆ 7.086253 ┆ working_a │
│          ┆ income     ┆ POP_4549_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 45-49,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ COL      ┆ Colombia   ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 20 to 24  ┆ 8.983095 ┆ 9.114774 ┆ working_a │
│          ┆            ┆ POP_2024_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 20-24,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
│ FIN      ┆ Finland    ┆ WB_WDI_SP_ ┆ Populatio ┆ … ┆ 55 to 59  ┆ 7.267521 ┆ 6.694983 ┆ working_a │
│          ┆            ┆ POP_5559_M ┆ n ages    ┆   ┆ years old ┆          ┆          ┆ ge        │
│          ┆            ┆ A_5Y       ┆ 55-59,    ┆   ┆           ┆          ┆          ┆           │
│          ┆            ┆            ┆ male (%…  ┆   ┆           ┆          ┆          ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘
shape: (3_710, 9)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_ ┆ INDICATOR ┆ INDICATOR ┆ … ┆ AGE_LABEL ┆ 2010      ┆ 2018      ┆ AGE_GROUP │
│ ---      ┆ LABEL     ┆ ---       ┆ _LABEL    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64       ┆ str       │
│          ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ TSS      ┆ Sub-Sahar ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 3.264992  ┆ 3.359498  ┆ retiremen │
│          ┆ an Africa ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆ (IDA &    ┆ _FE_ZS    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆ IBRD…     ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ DEU      ┆ Germany   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 80 years  ┆ 6.84563   ┆ 7.849763  ┆ retiremen │
│          ┆           ┆ _POP_80UP ┆ n ages 80 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ CPV      ┆ Cabo      ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 25020.0   ┆ 28946.0   ┆ retiremen │
│          ┆ Verde     ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _TO       ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ PRT      ┆ Portugal  ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 75 to 79  ┆ 4.518764  ┆ 4.536679  ┆ retiremen │
│          ┆           ┆ _POP_7579 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ 75-79,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ female …  ┆   ┆           ┆           ┆           ┆           │
│ USA      ┆ United    ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 14.455295 ┆ 16.804587 ┆ retiremen │
│          ┆ States    ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_ZS    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WLD      ┆ World     ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 to 69  ┆ 2.659007  ┆ 3.440843  ┆ retiremen │
│          ┆           ┆ _POP_6569 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ 65-69,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ female …  ┆   ┆           ┆           ┆           ┆           │
│ PRI      ┆ Puerto    ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 70 to 74  ┆ 3.858668  ┆ 5.442905  ┆ retiremen │
│          ┆ Rico      ┆ _POP_7074 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ 70-74,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ female …  ┆   ┆           ┆           ┆           ┆           │
│ MYS      ┆ Malaysia  ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 75 to 79  ┆ 0.744345  ┆ 0.926619  ┆ retiremen │
│          ┆           ┆ _POP_7579 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ t_age     │
│          ┆           ┆ _MA_5Y    ┆ 75-79,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ GBR      ┆ United    ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 16.338385 ┆ 18.25575  ┆ retiremen │
│          ┆ Kingdom   ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _TO_ZS    ┆ and above ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ (…        ┆   ┆           ┆           ┆           ┆           │
│ LCA      ┆ St. Lucia ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 6.473393  ┆ 7.337911  ┆ retiremen │
│          ┆           ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _MA_ZS    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [57]:
import polars as pl

countries_wb = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas, The","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo, Dem. Rep.","Congo, Rep.","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt, Arab Rep.","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia, The","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran, Islamic Rep.","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea, Rep.","Korea, Dem. People's Rep.","Kuwait","Kyrgyz Republic","Lao PDR","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia, Fed. Sts.","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovak Republic","Slovenia","Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","St. Kitts and Nevis","St. Lucia","St. Vincent and the Grenadines","Sudan","Suriname","Sweden","Switzerland","Syrian Arab Republic","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela, RB","Vietnam","West Bank and Gaza","Yemen, Rep.","Zambia","Zimbabwe"]

countries_wb_extended = countries_wb + [
    "Kosovo",
    "Macao SAR, China",
    "Hong Kong SAR, China"
]

widef_pl = (
    widef_pl
    .with_columns(
        pl.when(pl.col("REF_AREA_LABEL").str.contains("rkiye"))
        .then(pl.lit("Turkey"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Ivoire"))
        .then(pl.lit("Cote d'Ivoire"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Tome"))
        .then(pl.lit("Sao Tome and Principe"))
        .when(pl.col("REF_AREA_LABEL") == "Federal Republic of Somalia")
        .then(pl.lit("Somalia"))
        .otherwise(pl.col("REF_AREA_LABEL"))
        .alias("REF_AREA_LABEL")
    )
    .filter(pl.col("REF_AREA_LABEL").is_in(countries_wb_extended))
)

print(widef_pl["REF_AREA_LABEL"].n_unique())
print(widef_pl["REF_AREA_LABEL"].unique().sort().to_list())

196
['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

In [58]:
gdp_widef_pl = widef_pl.filter(
    pl.col('INDICATOR_LABEL').is_in([
        'GDP per capita (current US$)',
        'GDP per capita growth (annual %)'
    ])
)

gdp_widef_pl["INDICATOR_LABEL"].unique()

shape: (2,)
Series: 'INDICATOR_LABEL' [str]
[
	"GDP per capita (current US$)"
	"GDP per capita growth (annual …
]

In [59]:
import polars as pl

countries_wb = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas, The","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo, Dem. Rep.","Congo, Rep.","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt, Arab Rep.","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia, The","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran, Islamic Rep.","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea, Rep.","Korea, Dem. People's Rep.","Kuwait","Kyrgyz Republic","Lao PDR","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia, Fed. Sts.","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovak Republic","Slovenia","Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","St. Kitts and Nevis","St. Lucia","St. Vincent and the Grenadines","Sudan","Suriname","Sweden","Switzerland","Syrian Arab Republic","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela, RB","Vietnam","West Bank and Gaza","Yemen, Rep.","Zambia","Zimbabwe"]

countries_wb_extended = countries_wb + [
    "Kosovo",
    "Macao SAR, China",
    "Hong Kong SAR, China",
    "Taiwan, China"
]

# Fix typos in all 3 datasets
for df_name, df in [("widef_pl", widef_pl), ("hci_pl", hci_pl), ("hcp_pl", hcp_pl)]:
    df = df.with_columns(
        pl.when(pl.col("REF_AREA_LABEL").str.contains("rkiye"))
        .then(pl.lit("Turkey"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Ivoire"))
        .then(pl.lit("Cote d'Ivoire"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Tome"))
        .then(pl.lit("Sao Tome and Principe"))
        .when(pl.col("REF_AREA_LABEL") == "Viet Nam")
        .then(pl.lit("Vietnam"))
        .when(pl.col("REF_AREA_LABEL") == "Federal Republic of Somalia")
        .then(pl.lit("Somalia"))
        .otherwise(pl.col("REF_AREA_LABEL"))
        .alias("REF_AREA_LABEL")
    )
    if df_name == "widef_pl":
        widef_pl = df
    elif df_name == "hci_pl":
        hci_pl = df
    else:
        hcp_pl = df

# Define countries_all3
countries_all3 = (
    set(widef_pl["REF_AREA_LABEL"].unique().to_list()) &
    set(hci_pl["REF_AREA_LABEL"].unique().to_list()) &
    set(hcp_pl["REF_AREA_LABEL"].unique().to_list())
)

print(f"countries_all3 defined with {len(countries_all3)} countries")

countries_all3 defined with 162 countries

In [60]:
#Putting it all together into the "new" widef_pl dataset:

new_widef_pl = (
    widef_pl
    # Keep only filtered countries
    .filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
    
    # Add AGE_GROUP column
    .with_columns(
        pl.when(pl.col("INDICATOR").str.contains("SP_POP_2024|SP_POP_2529|SP_POP_3034|SP_POP_3539|SP_POP_4044|SP_POP_4549|SP_POP_5054|SP_POP_5559|SP_POP_6064"))
        .then(pl.lit("working_age"))
        .when(pl.col("INDICATOR").str.contains("SP_POP_65UP|SP_POP_6569|SP_POP_7074|SP_POP_7579|SP_POP_80UP"))
        .then(pl.lit("retirement_age"))
        .otherwise(pl.lit("other"))
        .alias("AGE_GROUP")
    )
    
    # Keep only the INDICATOR_LABEL values
    .filter(
        pl.col("INDICATOR_LABEL").is_in([
            'GDP per capita (current US$)',
            'GDP per capita growth (annual %)'
        ]) |
        pl.col("AGE_GROUP").is_in(["working_age", "retirement_age"])
    )
)

print(new_widef_pl.shape)
new_widef_pl.head()

(5508, 9)

shape: (5, 9)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_ ┆ INDICATOR ┆ INDICATOR ┆ … ┆ AGE_LABEL ┆ 2010      ┆ 2018      ┆ AGE_GROUP │
│ ---      ┆ LABEL     ┆ ---       ┆ _LABEL    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64       ┆ str       │
│          ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ LTU      ┆ Lithuania ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.999132  ┆ 7.448568  ┆ working_a │
│          ┆           ┆ _POP_4549 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 45-49,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ BEL      ┆ Belgium   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 50 to 54  ┆ 7.232739  ┆ 7.256239  ┆ working_a │
│          ┆           ┆ _POP_5054 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 50-54,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ DEU      ┆ Germany   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 80 years  ┆ 6.84563   ┆ 7.849763  ┆ retiremen │
│          ┆           ┆ _POP_80UP ┆ n ages 80 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ ISR      ┆ Israel    ┆ WB_WDI_NY ┆ GDP per   ┆ … ┆ All age   ┆ 31439.088 ┆ 42362.665 ┆ other     │
│          ┆           ┆ _GDP_PCAP ┆ capita    ┆   ┆ ranges or ┆ 703       ┆ 275       ┆           │
│          ┆           ┆ _CD       ┆ (current  ┆   ┆ no breakd ┆           ┆           ┆           │
│          ┆           ┆           ┆ US$)      ┆   ┆ own…      ┆           ┆           ┆           │
│ BIH      ┆ Bosnia    ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.431352  ┆ 6.273706  ┆ working_a │
│          ┆ and Herze ┆ _POP_4549 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆ govina    ┆ _FE_5Y    ┆ 45-49,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ female …  ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [61]:
hci_pl = hci_pl.select([
    'REF_AREA','REF_AREA_LABEL', 'SEX_LABEL','2010', '2018'])

hci_pl.head()

shape: (5, 5)
┌──────────┬────────────────┬───────────┬──────────┬──────────┐
│ REF_AREA ┆ REF_AREA_LABEL ┆ SEX_LABEL ┆ 2010     ┆ 2018     │
│ ---      ┆ ---            ┆ ---       ┆ ---      ┆ ---      │
│ str      ┆ str            ┆ str       ┆ f64      ┆ f64      │
╞══════════╪════════════════╪═══════════╪══════════╪══════════╡
│ AFG      ┆ Afghanistan    ┆ Female    ┆ 0.771392 ┆ 0.803774 │
│ AFG      ┆ Afghanistan    ┆ Male      ┆ 0.7252   ┆ 0.758776 │
│ AFG      ┆ Afghanistan    ┆ Total     ┆ 0.747581 ┆ 0.780382 │
│ AFG      ┆ Afghanistan    ┆ Female    ┆ null     ┆ 6.795722 │
│ AFG      ┆ Afghanistan    ┆ Male      ┆ null     ┆ 9.544137 │
└──────────┴────────────────┴───────────┴──────────┴──────────┘

In [62]:
#Standardizing the country names in the HCI dataset to match those in the World Bank dataset:

countries_wb_extended = countries_wb + [
    "Kosovo",
    "Macao SAR, China",
    "Hong Kong SAR, China",
    "Taiwan, China"
]

hci_pl = (
    hci_pl
    .with_columns(
        pl.when(pl.col("REF_AREA_LABEL") == "Turkiye")
        .then(pl.lit("Turkey"))
        .when(pl.col("REF_AREA_LABEL") == "Viet Nam")
        .then(pl.lit("Vietnam"))
        .otherwise(pl.col("REF_AREA_LABEL"))
        .alias("REF_AREA_LABEL")
    )
    .filter(pl.col("REF_AREA_LABEL").is_in(countries_wb_extended))
)

print(hci_pl["REF_AREA_LABEL"].n_unique())
print(hci_pl["REF_AREA_LABEL"].unique().sort().to_list())

174
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Sweden', 'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

In [63]:
#Standardizing the country names in the HCP dataset to match those in the World Bank dataset:

import polars as pl

countries_wb = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas, The","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo, Dem. Rep.","Congo, Rep.","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt, Arab Rep.","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia, The","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran, Islamic Rep.","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea, Rep.","Korea, Dem. People's Rep.","Kuwait","Kyrgyz Republic","Lao PDR","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia, Fed. Sts.","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovak Republic","Slovenia","Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","St. Kitts and Nevis","St. Lucia","St. Vincent and the Grenadines","Sudan","Suriname","Sweden","Switzerland","Syrian Arab Republic","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela, RB","Vietnam","West Bank and Gaza","Yemen, Rep.","Zambia","Zimbabwe"]

hcp_pl = (
    hcp_pl
    .with_columns(
        pl.when(pl.col("REF_AREA_LABEL") == "Turkiye")
        .then(pl.lit("Turkey"))
        .when(pl.col("REF_AREA_LABEL") == "Viet Nam")
        .then(pl.lit("Vietnam"))
        .otherwise(pl.col("REF_AREA_LABEL"))
        .alias("REF_AREA_LABEL")
    )
    .filter(pl.col("REF_AREA_LABEL").is_in(countries_wb_extended))
)

print(hcp_pl["REF_AREA_LABEL"].n_unique())
print(hcp_pl["REF_AREA_LABEL"].unique().sort().to_list())

182
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Taiwan, China', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

In [64]:
# Get unique countries from each dataset
countries_widef = set(widef_pl["REF_AREA_LABEL"].unique().to_list())
countries_hci = set(hci_pl["REF_AREA_LABEL"].unique().to_list())
countries_hcp = set(hcp_pl["REF_AREA_LABEL"].unique().to_list())

# Find countries in ALL 3
countries_all3 = countries_widef & countries_hci & countries_hcp

# Find what's being discarded from each
only_in_widef = countries_widef - countries_all3
only_in_hci = countries_hci - countries_all3
only_in_hcp = countries_hcp - countries_all3

print(f"Countries in ALL 3 datasets: {len(countries_all3)}")
print(f"\nDiscarded - only in widef_pl: {sorted(only_in_widef)}")
print(f"\nDiscarded - only in hci_pl: {sorted(only_in_hci)}")
print(f"\nDiscarded - only in hcp_pl: {sorted(only_in_hcp)}")

# Filter all 3 datasets to keep only common countries
widef_pl = widef_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hci_pl   = hci_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hcp_pl   = hcp_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))

print(f"\nFinal shape widef_pl: {widef_pl.shape}")
print(f"Final shape hci_pl:   {hci_pl.shape}")
print(f"Final shape hcp_pl:   {hcp_pl.shape}")

Countries in ALL 3 datasets: 162

Discarded - only in widef_pl: ['Andorra', 'Antigua and Barbuda', 'Bahamas, The', 'Barbados', 'Belize', 'Bolivia', 'Cabo Verde', 'Cuba', 'Djibouti', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Grenada', 'Guinea-Bissau', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Libya', 'Liechtenstein', 'Maldives', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'Palau', 'San Marino', 'Seychelles', 'Somalia', 'St. Kitts and Nevis', 'Suriname', 'Syrian Arab Republic', 'Turkmenistan', 'Tuvalu', 'Venezuela, RB']

Discarded - only in hci_pl: ['Antigua and Barbuda', 'Dominica', 'Grenada', 'Kiribati', 'Kosovo', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Nauru', 'Palau', 'Seychelles', 'St. Kitts and Nevis', 'Tuvalu']

Discarded - only in hcp_pl: ['Bahamas, The', 'Barbados', 'Belize', 'Bolivia', 'Cabo Verde', 'Cuba', 'Djibouti', 'Equatorial Guinea', 'Eritrea', 'Guinea-Bissau', "Korea, Dem. People's Rep.", 'Libya', 'Maldives', 'Sao Tome and Principe', 'Somalia', 'Suriname', 'Syrian Arab Republic', 'Taiwan, China', 'Turkmenistan', 'Venezuela, RB']

Final shape widef_pl: (207667, 9)
Final shape hci_pl:   (4069, 5)
Final shape hcp_pl:   (324, 55)

In [65]:
hcp_pl = pl.read_csv(r"C:\Users\Beatriz Fernandes\Desktop\IronHack\Week by Week\W4\first_project\data\raw\WB_HCP_EMP_2WAP_A_WIDEF.csv")
hcp_pl.head()

hcp_pl = hcp_pl.select([
    'REF_AREA','REF_AREA_LABEL', 'SEX_LABEL', '2010', '2018'])

hcp_pl.head()

shape: (5, 5)
┌──────────┬────────────────┬───────────┬────────┬────────┐
│ REF_AREA ┆ REF_AREA_LABEL ┆ SEX_LABEL ┆ 2010   ┆ 2018   │
│ ---      ┆ ---            ┆ ---       ┆ ---    ┆ ---    │
│ str      ┆ str            ┆ str       ┆ f64    ┆ f64    │
╞══════════╪════════════════╪═══════════╪════════╪════════╡
│ AFG      ┆ Afghanistan    ┆ Female    ┆ 16.43  ┆ 20.004 │
│ AFG      ┆ Afghanistan    ┆ Total     ┆ 52.175 ┆ 49.57  │
│ AGO      ┆ Angola         ┆ Female    ┆ 84.229 ┆ 82.405 │
│ AGO      ┆ Angola         ┆ Total     ┆ 87.855 ┆ 85.693 │
│ ALB      ┆ Albania        ┆ Female    ┆ 52.364 ┆ 56.938 │
└──────────┴────────────────┴───────────┴────────┴────────┘

In [66]:
print("new_widef_pl columns:", new_widef_pl.columns)
print("hcp_pl columns:", hcp_pl.columns)
print("hci_pl columns:", hci_pl.columns)

new_widef_pl_cleaned_countries = new_widef_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hcp_pl_cleaned_countries = hcp_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hci_pl_cleaned_countries = hci_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))

display(new_widef_pl_cleaned_countries)
display(hcp_pl_cleaned_countries)
display(hci_pl_cleaned_countries)

new_widef_pl columns: ['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', '2010', '2018', 'AGE_GROUP']
hcp_pl columns: ['REF_AREA', 'REF_AREA_LABEL', 'SEX_LABEL', '2010', '2018']
hci_pl columns: ['REF_AREA', 'REF_AREA_LABEL', 'SEX_LABEL', '2010', '2018']

shape: (5_508, 9)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_ ┆ INDICATOR ┆ INDICATOR ┆ … ┆ AGE_LABEL ┆ 2010      ┆ 2018      ┆ AGE_GROUP │
│ ---      ┆ LABEL     ┆ ---       ┆ _LABEL    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64       ┆ str       │
│          ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ LTU      ┆ Lithuania ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.999132  ┆ 7.448568  ┆ working_a │
│          ┆           ┆ _POP_4549 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 45-49,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ BEL      ┆ Belgium   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 50 to 54  ┆ 7.232739  ┆ 7.256239  ┆ working_a │
│          ┆           ┆ _POP_5054 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 50-54,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ DEU      ┆ Germany   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 80 years  ┆ 6.84563   ┆ 7.849763  ┆ retiremen │
│          ┆           ┆ _POP_80UP ┆ n ages 80 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _FE_5Y    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ ISR      ┆ Israel    ┆ WB_WDI_NY ┆ GDP per   ┆ … ┆ All age   ┆ 31439.088 ┆ 42362.665 ┆ other     │
│          ┆           ┆ _GDP_PCAP ┆ capita    ┆   ┆ ranges or ┆ 703       ┆ 275       ┆           │
│          ┆           ┆ _CD       ┆ (current  ┆   ┆ no breakd ┆           ┆           ┆           │
│          ┆           ┆           ┆ US$)      ┆   ┆ own…      ┆           ┆           ┆           │
│ BIH      ┆ Bosnia    ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 45 to 49  ┆ 7.431352  ┆ 6.273706  ┆ working_a │
│          ┆ and Herze ┆ _POP_4549 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆ govina    ┆ _FE_5Y    ┆ 45-49,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ female …  ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ LCA      ┆ St. Lucia ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 65 years  ┆ 6.473393  ┆ 7.337911  ┆ retiremen │
│          ┆           ┆ _POP_65UP ┆ n ages 65 ┆   ┆ old and   ┆           ┆           ┆ t_age     │
│          ┆           ┆ _MA_ZS    ┆ and       ┆   ┆ over      ┆           ┆           ┆           │
│          ┆           ┆           ┆ above, …  ┆   ┆           ┆           ┆           ┆           │
│ COL      ┆ Colombia  ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 20 to 24  ┆ 8.983095  ┆ 9.114774  ┆ working_a │
│          ┆           ┆ _POP_2024 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 20-24,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ FIN      ┆ Finland   ┆ WB_WDI_SP ┆ Populatio ┆ … ┆ 55 to 59  ┆ 7.267521  ┆ 6.694983  ┆ working_a │
│          ┆           ┆ _POP_5559 ┆ n ages    ┆   ┆ years old ┆           ┆           ┆ ge        │
│          ┆           ┆ _MA_5Y    ┆ 55-59,    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ male (%…  ┆   ┆           ┆           ┆           ┆           │
│ LCA      ┆ St. Lucia ┆ WB_WDI_NY ┆ GDP per   ┆ … ┆ All age   ┆ -0.27875  ┆ 2.494452  ┆ other     │
│          ┆           ┆ _GDP_PCAP ┆ capita    ┆   ┆ ranges or ┆           ┆           ┆           │
│          ┆           ┆ _KD_ZG    ┆ growth    ┆   ┆ no breakd ┆           ┆           ┆           │
│          ┆           ┆           ┆ (annual … ┆   ┆ own…      ┆           ┆           ┆           │
│ ALB      ┆ Albania   ┆ WB_WDI_NY ┆ GDP per   ┆ … ┆ All age   ┆ 4149.1446 ┆ 5897.6545 ┆ other     │
│          ┆           ┆ _GDP_PCAP ┆ capita    ┆   ┆ ranges or ┆ 99        ┆ 26        ┆           │
│          ┆           ┆ _CD       ┆ (current  ┆   ┆ no breakd ┆           ┆           ┆           │
│          ┆           ┆           ┆ US$)      ┆   ┆ own…      ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (320, 5)
┌──────────┬────────────────┬───────────┬────────┬────────┐
│ REF_AREA ┆ REF_AREA_LABEL ┆ SEX_LABEL ┆ 2010   ┆ 2018   │
│ ---      ┆ ---            ┆ ---       ┆ ---    ┆ ---    │
│ str      ┆ str            ┆ str       ┆ f64    ┆ f64    │
╞══════════╪════════════════╪═══════════╪════════╪════════╡
│ AFG      ┆ Afghanistan    ┆ Female    ┆ 16.43  ┆ 20.004 │
│ AFG      ┆ Afghanistan    ┆ Total     ┆ 52.175 ┆ 49.57  │
│ AGO      ┆ Angola         ┆ Female    ┆ 84.229 ┆ 82.405 │
│ AGO      ┆ Angola         ┆ Total     ┆ 87.855 ┆ 85.693 │
│ ALB      ┆ Albania        ┆ Female    ┆ 52.364 ┆ 56.938 │
│ …        ┆ …              ┆ …         ┆ …      ┆ …      │
│ ZAF      ┆ South Africa   ┆ Total     ┆ 65.453 ┆ 67.223 │
│ ZMB      ┆ Zambia         ┆ Female    ┆ 60.901 ┆ 62.164 │
│ ZMB      ┆ Zambia         ┆ Total     ┆ 71.815 ┆ 71.376 │
│ ZWE      ┆ Zimbabwe       ┆ Female    ┆ 69.43  ┆ 68.527 │
│ ZWE      ┆ Zimbabwe       ┆ Total     ┆ 74.556 ┆ 73.615 │
└──────────┴────────────────┴───────────┴────────┴────────┘

shape: (4_069, 5)
┌──────────┬────────────────┬───────────┬────────────┬────────────┐
│ REF_AREA ┆ REF_AREA_LABEL ┆ SEX_LABEL ┆ 2010       ┆ 2018       │
│ ---      ┆ ---            ┆ ---       ┆ ---        ┆ ---        │
│ str      ┆ str            ┆ str       ┆ f64        ┆ f64        │
╞══════════╪════════════════╪═══════════╪════════════╪════════════╡
│ AFG      ┆ Afghanistan    ┆ Female    ┆ 0.771392   ┆ 0.803774   │
│ AFG      ┆ Afghanistan    ┆ Male      ┆ 0.7252     ┆ 0.758776   │
│ AFG      ┆ Afghanistan    ┆ Total     ┆ 0.747581   ┆ 0.780382   │
│ AFG      ┆ Afghanistan    ┆ Female    ┆ null       ┆ 6.795722   │
│ AFG      ┆ Afghanistan    ┆ Male      ┆ null       ┆ 9.544137   │
│ …        ┆ …              ┆ …         ┆ …          ┆ …          │
│ ZWE      ┆ Zimbabwe       ┆ Male      ┆ 0.907738   ┆ 0.946212   │
│ ZWE      ┆ Zimbabwe       ┆ Total     ┆ 0.913664   ┆ 0.950691   │
│ ZWE      ┆ Zimbabwe       ┆ Female    ┆ 392.212585 ┆ null       │
│ ZWE      ┆ Zimbabwe       ┆ Male      ┆ 395.731903 ┆ null       │
│ ZWE      ┆ Zimbabwe       ┆ Total     ┆ 394.198059 ┆ 396.138824 │
└──────────┴────────────────┴───────────┴────────────┴────────────┘

In [67]:
# Fix typos in hcp_pl
hcp_pl = hcp_pl.with_columns(
    pl.when(pl.col("REF_AREA_LABEL") == "Turkiye")
    .then(pl.lit("Turkey"))
    .when(pl.col("REF_AREA_LABEL") == "Viet Nam")
    .then(pl.lit("Vietnam"))
    .otherwise(pl.col("REF_AREA_LABEL"))
    .alias("REF_AREA_LABEL")
)

# Rerun intersection
countries_widef = set(widef_pl["REF_AREA_LABEL"].unique().to_list())
countries_hci = set(hci_pl["REF_AREA_LABEL"].unique().to_list())
countries_hcp = set(hcp_pl["REF_AREA_LABEL"].unique().to_list())
countries_all3 = countries_widef & countries_hci & countries_hcp

# Rerun cleaned country filters
new_widef_pl_cleaned_countries = new_widef_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hcp_pl_cleaned_countries = hcp_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))
hci_pl_cleaned_countries = hci_pl.filter(pl.col("REF_AREA_LABEL").is_in(countries_all3))

# Verify
print("new_widef_pl:", new_widef_pl_cleaned_countries["REF_AREA_LABEL"].n_unique())
print("hcp_pl:", hcp_pl_cleaned_countries["REF_AREA_LABEL"].n_unique())
print("hci_pl:", hci_pl_cleaned_countries["REF_AREA_LABEL"].n_unique())

new_widef_pl: 162
hcp_pl: 162
hci_pl: 162

In [68]:
#Fixes after cleaning - removing "Female" from HCP and dropping "INDICATOR" from widef_pl_cleaned_countries:
hcp_pl_cleaned_countries = hcp_pl_cleaned_countries.filter(pl.col("SEX_LABEL") == "Total")

new_widef_pl_cleaned_countries = new_widef_pl_cleaned_countries.drop("INDICATOR")
new_widef_pl_cleaned_countries.head()

shape: (5, 8)
┌──────────┬────────────┬────────────┬───────────┬────────────┬────────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_L ┆ INDICATOR_ ┆ SEX_LABEL ┆ AGE_LABEL  ┆ 2010       ┆ 2018      ┆ AGE_GROUP │
│ ---      ┆ ABEL       ┆ LABEL      ┆ ---       ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str      ┆ ---        ┆ ---        ┆ str       ┆ str        ┆ f64        ┆ f64       ┆ str       │
│          ┆ str        ┆ str        ┆           ┆            ┆            ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪════════════╪════════════╪═══════════╪═══════════╡
│ LTU      ┆ Lithuania  ┆ Population ┆ Male      ┆ 45 to 49   ┆ 7.999132   ┆ 7.448568  ┆ working_a │
│          ┆            ┆ ages       ┆           ┆ years old  ┆            ┆           ┆ ge        │
│          ┆            ┆ 45-49,     ┆           ┆            ┆            ┆           ┆           │
│          ┆            ┆ male (%…   ┆           ┆            ┆            ┆           ┆           │
│ BEL      ┆ Belgium    ┆ Population ┆ Male      ┆ 50 to 54   ┆ 7.232739   ┆ 7.256239  ┆ working_a │
│          ┆            ┆ ages       ┆           ┆ years old  ┆            ┆           ┆ ge        │
│          ┆            ┆ 50-54,     ┆           ┆            ┆            ┆           ┆           │
│          ┆            ┆ male (%…   ┆           ┆            ┆            ┆           ┆           │
│ DEU      ┆ Germany    ┆ Population ┆ Female    ┆ 80 years   ┆ 6.84563    ┆ 7.849763  ┆ retiremen │
│          ┆            ┆ ages 80    ┆           ┆ old and    ┆            ┆           ┆ t_age     │
│          ┆            ┆ and above, ┆           ┆ over       ┆            ┆           ┆           │
│          ┆            ┆ …          ┆           ┆            ┆            ┆           ┆           │
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ All age    ┆ 31439.0887 ┆ 42362.665 ┆ other     │
│          ┆            ┆ capita     ┆           ┆ ranges or  ┆ 03         ┆ 275       ┆           │
│          ┆            ┆ (current   ┆           ┆ no         ┆            ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆ breakdown… ┆            ┆           ┆           │
│ BIH      ┆ Bosnia and ┆ Population ┆ Female    ┆ 45 to 49   ┆ 7.431352   ┆ 6.273706  ┆ working_a │
│          ┆ Herzegovin ┆ ages       ┆           ┆ years old  ┆            ┆           ┆ ge        │
│          ┆ a          ┆ 45-49,     ┆           ┆            ┆            ┆           ┆           │
│          ┆            ┆ female …   ┆           ┆            ┆            ┆           ┆           │
└──────────┴────────────┴────────────┴───────────┴────────────┴────────────┴───────────┴───────────┘

In [69]:
print("new_widef_pl_cleaned_countries columns:", new_widef_pl_cleaned_countries.columns)
print(" hcp_pl_cleaned_countries columns:", hcp_pl_cleaned_countries.columns)
print("hci_pl_cleaned_countries columns:", hci_pl_cleaned_countries.columns)

new_widef_pl_cleaned_countries columns: ['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', '2010', '2018', 'AGE_GROUP']
 hcp_pl_cleaned_countries columns: ['REF_AREA', 'REF_AREA_LABEL', 'SEX_LABEL', '2010', '2018']
hci_pl_cleaned_countries columns: ['REF_AREA', 'REF_AREA_LABEL', 'SEX_LABEL', '2010', '2018']

In [82]:
#Joining the datasets on REF_AREA_LABEL and REF_AREA (which should be the same in all 3), but realizing Female and Male have to be deleted otherwise they will create a lot of null values.

# Filter to TOTAL only before joining
new_widef_total = new_widef_pl_cleaned_countries.filter(pl.col('SEX_LABEL') == 'Total')
hcp_total = hcp_pl_cleaned_countries.filter(pl.col('SEX_LABEL') == 'Total')
hci_total = hci_pl_cleaned_countries.filter(pl.col('SEX_LABEL') == 'Total')

# Join keys
join_keys = ['REF_AREA', 'REF_AREA_LABEL', 'SEX_LABEL']

# First join
merged = new_widef_total.join(
    hcp_total,
    on=join_keys,
    how='left',
    suffix='_hcp'
)

# Second join
merged = merged.join(
    hci_total,
    on=join_keys,
    how='left',
    suffix='_hci'
)

display(merged)

shape: (5_580, 12)
┌──────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ REF_AREA ┆ REF_AREA_L ┆ INDICATOR_ ┆ SEX_LABEL ┆ … ┆ 2010_hcp ┆ 2018_hcp ┆ 2010_hci  ┆ 2018_hci  │
│ ---      ┆ ABEL       ┆ LABEL      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---       │
│ str      ┆ ---        ┆ ---        ┆ str       ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64       │
│          ┆ str        ┆ str        ┆           ┆   ┆          ┆          ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ … ┆ 66.145   ┆ 69.561   ┆ 0.939214  ┆ 0.948518  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ … ┆ 66.145   ┆ 69.561   ┆ 13.743439 ┆ 13.762948 │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ … ┆ 66.145   ┆ 69.561   ┆ 0.718269  ┆ 0.763064  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ … ┆ 66.145   ┆ 69.561   ┆ 0.708901  ┆ 0.752196  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ISR      ┆ Israel     ┆ GDP per    ┆ Total     ┆ … ┆ 66.145   ┆ 69.561   ┆ 0.727328  ┆ 0.773985  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ ALB      ┆ Albania    ┆ GDP per    ┆ Total     ┆ … ┆ 61.753   ┆ 65.072   ┆ 0.554806  ┆ 0.640916  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ALB      ┆ Albania    ┆ GDP per    ┆ Total     ┆ … ┆ 61.753   ┆ 65.072   ┆ 7.382478  ┆ 8.851396  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ALB      ┆ Albania    ┆ GDP per    ┆ Total     ┆ … ┆ 61.753   ┆ 65.072   ┆ 0.768125  ┆ 0.886766  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ALB      ┆ Albania    ┆ GDP per    ┆ Total     ┆ … ┆ 61.753   ┆ 65.072   ┆ 0.986695  ┆ 0.990978  │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
│ ALB      ┆ Albania    ┆ GDP per    ┆ Total     ┆ … ┆ 61.753   ┆ 65.072   ┆ 397.22686 ┆ 429.32901 │
│          ┆            ┆ capita     ┆           ┆   ┆          ┆          ┆ 8         ┆           │
│          ┆            ┆ (current   ┆           ┆   ┆          ┆          ┆           ┆           │
│          ┆            ┆ US$)       ┆           ┆   ┆          ┆          ┆           ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [80]:
merged.columns

['REF_AREA',
 'REF_AREA_LABEL',
 'INDICATOR_LABEL',
 'SEX_LABEL',
 'AGE_LABEL',
 '2010',
 '2018',
 'AGE_GROUP',
 '2010_hcp',
 '2018_hcp',
 '2010_hci',
 '2018_hci']