In [12]:
import pandas as pd
import numpy as np
import yaml

with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)

#config["input_data"]["file_alex"]
hci_df = pd.read_csv(config["input_data"]["file_alex"])

In [13]:
hci_df.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,TIME_PERIOD,OBS_VALUE,DATABASE_ID,DATABASE_ID_LABEL,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2010,0.840845,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2018,0.846043,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2020,0.848294,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,EAS,East Asia & Pacific,WB_HCI_ASR,Adult Survival Rate,_T,...,2010,0.900628,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,EAS,East Asia & Pacific,WB_HCI_ASR,Adult Survival Rate,_T,...,2018,0.861863,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY

In [14]:
# we change the name of the columns in lower case.
hci_df.columns = hci_df.columns.str.lower()
hci_df.head()

,structure,structure_id,action,freq,freq_label,ref_area,ref_area_label,indicator,indicator_label,sex,...,time_period,obs_value,database_id,database_id_label,unit_mult,unit_mult_label,unit_type,unit_type_label,time_format,time_format_label
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2010,0.840845,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2018,0.846043,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,WLD,World,WB_HCI_ASR,Adult Survival Rate,_T,...,2020,0.848294,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,EAS,East Asia & Pacific,WB_HCI_ASR,Adult Survival Rate,_T,...,2010,0.900628,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,EAS,East Asia & Pacific,WB_HCI_ASR,Adult Survival Rate,_T,...,2018,0.861863,WB_HCI,Human Capital Index (HCI),0,Units,RATIO,Ratio,602,CCYY

In [15]:
hci_df.columns

Index(['structure', 'structure_id', 'action', 'freq', 'freq_label', 'ref_area',
       'ref_area_label', 'indicator', 'indicator_label', 'sex', 'sex_label',
       'age', 'age_label', 'urbanisation', 'urbanisation_label',
       'unit_measure', 'unit_measure_label', 'comp_breakdown_1',
       'comp_breakdown_1_label', 'comp_breakdown_2', 'comp_breakdown_2_label',
       'comp_breakdown_3', 'comp_breakdown_3_label', 'time_period',
       'obs_value', 'database_id', 'database_id_label', 'unit_mult',
       'unit_mult_label', 'unit_type', 'unit_type_label', 'time_format',
       'time_format_label'],
      dtype='str')

In [16]:
# we drop all the columns that are not: "ref_area", "ref_area_label", "indicator", "sex" and "time_period"
hci_df = hci_df[["ref_area", "ref_area_label", "indicator", "sex", "time_period"]]
hci_df

      ref_area       ref_area_label    indicator sex  time_period
0          WLD                World   WB_HCI_ASR  _T         2010
1          WLD                World   WB_HCI_ASR  _T         2018
2          WLD                World   WB_HCI_ASR  _T         2020
3          EAS  East Asia & Pacific   WB_HCI_ASR  _T         2010
4          EAS  East Asia & Pacific   WB_HCI_ASR  _T         2018
...        ...                  ...          ...  ..          ...
15034      ZMB               Zambia  WB_HCI_TEST   F         2018
15035      ZMB               Zambia  WB_HCI_TEST   F         2020
15036      ZWE             Zimbabwe  WB_HCI_TEST   F         2010
15037      ZWE             Zimbabwe  WB_HCI_TEST   F         2018
15038      ZWE             Zimbabwe  WB_HCI_TEST   F         2020

[15039 rows x 5 columns]

In [17]:
# we will filter the dataframe to only keep the indicators: "WB_HCI_HCI", "WB_HCI_LAYS" and "WB_HCI_ASR"
hci_df = hci_df[hci_df["indicator"].isin(["WB_HCI_HCI", "WB_HCI_LAYS", "WB_HCI_ASR"])]
hci_df

      ref_area       ref_area_label    indicator sex  time_period
0          WLD                World   WB_HCI_ASR  _T         2010
1          WLD                World   WB_HCI_ASR  _T         2018
2          WLD                World   WB_HCI_ASR  _T         2020
3          EAS  East Asia & Pacific   WB_HCI_ASR  _T         2010
4          EAS  East Asia & Pacific   WB_HCI_ASR  _T         2018
...        ...                  ...          ...  ..          ...
10021      ZMB               Zambia  WB_HCI_LAYS   F         2018
10022      ZMB               Zambia  WB_HCI_LAYS   F         2020
10023      ZWE             Zimbabwe  WB_HCI_LAYS   F         2010
10024      ZWE             Zimbabwe  WB_HCI_LAYS   F         2018
10025      ZWE             Zimbabwe  WB_HCI_LAYS   F         2020

[5013 rows x 5 columns]

In [18]:
# sort the dataframe by "ref_area" and "time_period" in ascending order
hci_df= hci_df.sort_values(by=["ref_area", "time_period"] , ascending=True)
hci_df

      ref_area ref_area_label    indicator sex  time_period
35         AFG    Afghanistan   WB_HCI_ASR  _T         2010
592        AFG    Afghanistan   WB_HCI_ASR   M         2010
1149       AFG    Afghanistan   WB_HCI_ASR   F         2010
3377       AFG    Afghanistan   WB_HCI_HCI  _T         2010
3934       AFG    Afghanistan   WB_HCI_HCI   M         2010
...        ...            ...          ...  ..          ...
4455       ZWE       Zimbabwe   WB_HCI_HCI   M         2020
5012       ZWE       Zimbabwe   WB_HCI_HCI   F         2020
8911       ZWE       Zimbabwe  WB_HCI_LAYS  _T         2020
9468       ZWE       Zimbabwe  WB_HCI_LAYS   M         2020
10025      ZWE       Zimbabwe  WB_HCI_LAYS   F         2020

[5013 rows x 5 columns]

In [19]:
# Check for missing values
hci_df.isnull().sum()

ref_area          0
ref_area_label    0
indicator         0
sex               0
time_period       0
dtype: int64

In [20]:
# check for duplicates
hci_df.duplicated().sum()

np.int64(0)

In [21]:
# Make a list with the names of the countries in the World.
countries_wb = [
"Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria",
"Azerbaijan","Bahamas, The","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia",
"Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cabo Verde",
"Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros",
"Congo, Dem. Rep.","Congo, Rep.","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Denmark",
"Djibouti","Dominica","Dominican Republic","Ecuador","Egypt, Arab Rep.","El Salvador","Equatorial Guinea","Eritrea",
"Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia, The","Georgia","Germany","Ghana","Greece",
"Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran, Islamic Rep.","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati",
"Korea, Rep.","Korea, Dem. People's Rep.","Kuwait","Kyrgyz Republic","Lao PDR","Latvia","Lebanon","Lesotho","Liberia",
"Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta",
"Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia, Fed. Sts.","Moldova","Monaco","Mongolia","Montenegro",
"Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria",
"North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines",
"Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovak Republic","Slovenia",
"Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","St. Kitts and Nevis","St. Lucia",
"St. Vincent and the Grenadines","Sudan","Suriname","Sweden","Switzerland","Syrian Arab Republic","Tajikistan",
"Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu",
"Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu",
"Venezuela, RB","Vietnam","West Bank and Gaza","Yemen, Rep.","Zambia","Zimbabwe"
]

In [23]:
#This way we remove all the rows that are not in the list of countries. 
hci_df_filtered = hci_df[hci_df["ref_area_label"].isin(countries_wb)]
hci_df_filtered

      ref_area ref_area_label    indicator sex  time_period
35         AFG    Afghanistan   WB_HCI_ASR  _T         2010
592        AFG    Afghanistan   WB_HCI_ASR   M         2010
1149       AFG    Afghanistan   WB_HCI_ASR   F         2010
3377       AFG    Afghanistan   WB_HCI_HCI  _T         2010
3934       AFG    Afghanistan   WB_HCI_HCI   M         2010
...        ...            ...          ...  ..          ...
4455       ZWE       Zimbabwe   WB_HCI_HCI   M         2020
5012       ZWE       Zimbabwe   WB_HCI_HCI   F         2020
8911       ZWE       Zimbabwe  WB_HCI_LAYS  _T         2020
9468       ZWE       Zimbabwe  WB_HCI_LAYS   M         2020
10025      ZWE       Zimbabwe  WB_HCI_LAYS   F         2020

[4563 rows x 5 columns]

In [ ]:
#number of unique values in the ref_area_label column
hci_df_filtered["ref_area_label"].nunique()

169

In [26]:
# drop all the values "2020" in the time_period column
hci_df_filtered = hci_df_filtered[hci_df_filtered["time_period"] != 2020]
hci_df_filtered

      ref_area ref_area_label    indicator sex  time_period
35         AFG    Afghanistan   WB_HCI_ASR  _T         2010
592        AFG    Afghanistan   WB_HCI_ASR   M         2010
1149       AFG    Afghanistan   WB_HCI_ASR   F         2010
3377       AFG    Afghanistan   WB_HCI_HCI  _T         2010
3934       AFG    Afghanistan   WB_HCI_HCI   M         2010
...        ...            ...          ...  ..          ...
4454       ZWE       Zimbabwe   WB_HCI_HCI   M         2018
5011       ZWE       Zimbabwe   WB_HCI_HCI   F         2018
8910       ZWE       Zimbabwe  WB_HCI_LAYS  _T         2018
9467       ZWE       Zimbabwe  WB_HCI_LAYS   M         2018
10024      ZWE       Zimbabwe  WB_HCI_LAYS   F         2018

[3042 rows x 5 columns]