In [10]:
import pandas as pd
import polars as pl

wdi_pl = pl.read_csv("../data/raw/WB_WDI.csv")
display(wdi_pl)

wdi_df = pd.read_csv("../data/raw/WB_WDI.csv")
display(wdi_df)

shape: (9_032_658, 43)
┌─────────────┬────────────┬────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ STRUCTURE   ┆ STRUCTURE_ ┆ ACTION ┆ FREQ ┆ … ┆ TIME_FORMA ┆ UNIT_MULT_ ┆ OBS_STATUS ┆ OBS_CONF_L │
│ ---         ┆ ID         ┆ ---    ┆ ---  ┆   ┆ T_LABEL    ┆ LABEL      ┆ _LABEL     ┆ ABEL       │
│ str         ┆ ---        ┆ str    ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆ str        ┆        ┆      ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞═════════════╪════════════╪════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …          ┆ …      ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ datastructu ┆ WB.DATA360 ┆ I      ┆ A    ┆ … ┆ Annual     ┆ Units      ┆ Normal     ┆ Public     │
│ re          ┆ :DS_DATA36 ┆        ┆      ┆   ┆            ┆            ┆ value      ┆            │
│             ┆ 0(1.3)     ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
└─────────────┴────────────┴────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_SP_DYN_AMRT_MA,M,_T,_T,10P3M,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_SP_DYN_IMRT_IN,_T,_T,_T,DT_10P3BR_L,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_SP_DYN_IMRT_FE_IN,F,_T,_T,DT_10P3BR_L,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_SP_DYN_IMRT_MA_IN,M,_T,_T,DT_10P3BR_L,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_SH_DYN_NMRT,_T,_T,_T,DT_10P3BR_L,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9032653,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_SP_URB_TOTL_IN_ZS,_T,_T,_T,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
9032654,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_SP_URB_GROW,_T,_T,_T,PC_A,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
9032655,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_DT_DOD_DIMF_CD,_T,_T,_T,USD,...,Not Applicable,Not Applicable,Not Applicable,Currency,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
9032656,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_SH_DYN_AIDS_FE_ZS,_T,_T,_T,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
9032657,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_SH_HIV_INCD_YG,_T,_T,_T,PS,...,Not Applicable,Not Applicable,Not Applicable,Count (Integer),Two,World Development Indicators (WDI),Annual,Units,Normal value,Public