In [1]:
import pandas as pd
import polars as pl
import yaml

In [2]:
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [16]:
widef_pl = pl.read_csv(config["input_data"]["file1"])
widef_pl.head()

shape: (5, 106)
┌───────────────┬───────────────┬────────┬──────┬───┬───────────┬───────────┬───────────┬──────────┐
│ STRUCTURE     ┆ STRUCTURE_ID  ┆ ACTION ┆ FREQ ┆ … ┆ 2021      ┆ 2022      ┆ 2023      ┆ 2024     │
│ ---           ┆ ---           ┆ ---    ┆ ---  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str           ┆ str           ┆ str    ┆ str  ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════════╪═══════════════╪════════╪══════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 11.751292 ┆ 11.754866 ┆ 11.737018 ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 1.2619e10 ┆ 1.2799e10 ┆ 1.1877e10 ┆ 8.7202e9 │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 2274.0    ┆ 2274.0    ┆ null      ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 13.89779  ┆ 7.898441  ┆ 0.401935  ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
│ datastructure ┆ WB.DATA360:DS ┆ I      ┆ A    ┆ … ┆ 2.7884e10 ┆ 2.9520e10 ┆ 2.9526e10 ┆ null     │
│               ┆ _DATA360(1.3) ┆        ┆      ┆   ┆           ┆           ┆           ┆          │
└───────────────┴───────────────┴────────┴──────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
widef_pl.columns

['STRUCTURE',
 'STRUCTURE_ID',
 'ACTION',
 'FREQ',
 'REF_AREA',
 'INDICATOR',
 'SEX',
 'AGE',
 'URBANISATION',
 'UNIT_MEASURE',
 'COMP_BREAKDOWN_1',
 'COMP_BREAKDOWN_2',
 'COMP_BREAKDOWN_3',
 'AGG_METHOD',
 'UNIT_TYPE',
 'DECIMALS',
 'DATABASE_ID',
 'TIME_FORMAT',
 'COMMENT_TS',
 'UNIT_MULT',
 'DATA_SOURCE',
 'OBS_CONF',
 'OBS_STATUS',
 'FREQ_LABEL',
 'REF_AREA_LABEL',
 'INDICATOR_LABEL',
 'SEX_LABEL',
 'AGE_LABEL',
 'URBANISATION_LABEL',
 'UNIT_MEASURE_LABEL',
 'COMP_BREAKDOWN_1_LABEL',
 'COMP_BREAKDOWN_2_LABEL',
 'COMP_BREAKDOWN_3_LABEL',
 'AGG_METHOD_LABEL',
 'UNIT_TYPE_LABEL',
 'DECIMALS_LABEL',
 'DATABASE_ID_LABEL',
 'TIME_FORMAT_LABEL',
 'UNIT_MULT_LABEL',
 'OBS_STATUS_LABEL',
 'OBS_CONF_LABEL',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024']

In [5]:
widef_pl.columns

['STRUCTURE',
 'STRUCTURE_ID',
 'ACTION',
 'FREQ',
 'REF_AREA',
 'INDICATOR',
 'SEX',
 'AGE',
 'URBANISATION',
 'UNIT_MEASURE',
 'COMP_BREAKDOWN_1',
 'COMP_BREAKDOWN_2',
 'COMP_BREAKDOWN_3',
 'AGG_METHOD',
 'UNIT_TYPE',
 'DECIMALS',
 'DATABASE_ID',
 'TIME_FORMAT',
 'COMMENT_TS',
 'UNIT_MULT',
 'DATA_SOURCE',
 'OBS_CONF',
 'OBS_STATUS',
 'FREQ_LABEL',
 'REF_AREA_LABEL',
 'INDICATOR_LABEL',
 'SEX_LABEL',
 'AGE_LABEL',
 'URBANISATION_LABEL',
 'UNIT_MEASURE_LABEL',
 'COMP_BREAKDOWN_1_LABEL',
 'COMP_BREAKDOWN_2_LABEL',
 'COMP_BREAKDOWN_3_LABEL',
 'AGG_METHOD_LABEL',
 'UNIT_TYPE_LABEL',
 'DECIMALS_LABEL',
 'DATABASE_ID_LABEL',
 'TIME_FORMAT_LABEL',
 'UNIT_MULT_LABEL',
 'OBS_STATUS_LABEL',
 'OBS_CONF_LABEL',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024']

In [24]:
widef_pl = widef_pl.select([
    'REF_AREA', 'INDICATOR', 'SEX', 'AGE',
    'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL',
    '2010', '2018'
])

widef_pl.head()

shape: (5, 10)
┌──────────┬─────────────────┬─────┬─────┬───┬───────────┬─────────────────┬───────────┬───────────┐
│ REF_AREA ┆ INDICATOR       ┆ SEX ┆ AGE ┆ … ┆ SEX_LABEL ┆ AGE_LABEL       ┆ 2010      ┆ 2018      │
│ ---      ┆ ---             ┆ --- ┆ --- ┆   ┆ ---       ┆ ---             ┆ ---       ┆ ---       │
│ str      ┆ str             ┆ str ┆ str ┆   ┆ str       ┆ str             ┆ f64       ┆ f64       │
╞══════════╪═════════════════╪═════╪═════╪═══╪═══════════╪═════════════════╪═══════════╪═══════════╡
│ MDA      ┆ WB_WDI_AG_LND_F ┆ _T  ┆ _T  ┆ … ┆ Total     ┆ All age ranges  ┆ 11.400304 ┆ 11.752972 │
│          ┆ RST_ZS          ┆     ┆     ┆   ┆           ┆ or no           ┆           ┆           │
│          ┆                 ┆     ┆     ┆   ┆           ┆ breakdown…      ┆           ┆           │
│ PSE      ┆ WB_WDI_NY_GDP_F ┆ _T  ┆ _T  ┆ … ┆ Total     ┆ All age ranges  ┆ 9.4635e9  ┆ 1.3318e10 │
│          ┆ CST_KD          ┆     ┆     ┆   ┆           ┆ or no           ┆           ┆           │
│          ┆                 ┆     ┆     ┆   ┆           ┆ breakdown…      ┆           ┆           │
│ ECU      ┆ WB_WDI_AG_LND_P ┆ _T  ┆ _T  ┆ … ┆ Total     ┆ All age ranges  ┆ 2274.0    ┆ 2274.0    │
│          ┆ RCP_MM          ┆     ┆     ┆   ┆           ┆ or no           ┆           ┆           │
│          ┆                 ┆     ┆     ┆   ┆           ┆ breakdown…      ┆           ┆           │
│ SMR      ┆ WB_WDI_NY_GDP_M ┆ _T  ┆ _T  ┆ … ┆ Total     ┆ All age ranges  ┆ -5.473684 ┆ 1.493905  │
│          ┆ KTP_KD_ZG       ┆     ┆     ┆   ┆           ┆ or no           ┆           ┆           │
│          ┆                 ┆     ┆     ┆   ┆           ┆ breakdown…      ┆           ┆           │
│ NZL      ┆ WB_WDI_NY_TAX_N ┆ _T  ┆ _T  ┆ … ┆ Total     ┆ All age ranges  ┆ 1.9830e10 ┆ 2.6453e10 │
│          ┆ IND_KN          ┆     ┆     ┆   ┆           ┆ or no           ┆           ┆           │
│          ┆                 ┆     ┆     ┆   ┆           ┆ breakdown…      ┆           ┆           │
└──────────┴─────────────────┴─────┴─────┴───┴───────────┴─────────────────┴───────────┴───────────┘

In [7]:
widef_pl["SEX"].value_counts()
widef_pl.drop("AGE")

shape: (294_796, 10)
┌──────────┬─────────────┬─────┬─────────────┬───┬─────────────┬───────────┬───────────┬───────────┐
│ REF_AREA ┆ INDICATOR   ┆ SEX ┆ REF_AREA_LA ┆ … ┆ AGE_LABEL   ┆ 2010      ┆ 2018      ┆ 2020      │
│ ---      ┆ ---         ┆ --- ┆ BEL         ┆   ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ str         ┆ str ┆ ---         ┆   ┆ str         ┆ f64       ┆ f64       ┆ f64       │
│          ┆             ┆     ┆ str         ┆   ┆             ┆           ┆           ┆           │
╞══════════╪═════════════╪═════╪═════════════╪═══╪═════════════╪═══════════╪═══════════╪═══════════╡
│ MDA      ┆ WB_WDI_AG_L ┆ _T  ┆ Moldova     ┆ … ┆ All age     ┆ 11.400304 ┆ 11.752972 ┆ 11.753222 │
│          ┆ ND_FRST_ZS  ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ PSE      ┆ WB_WDI_NY_G ┆ _T  ┆ West Bank   ┆ … ┆ All age     ┆ 9.4635e9  ┆ 1.3318e10 ┆ 1.1880e10 │
│          ┆ DP_FCST_KD  ┆     ┆ and Gaza    ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ ECU      ┆ WB_WDI_AG_L ┆ _T  ┆ Ecuador     ┆ … ┆ All age     ┆ 2274.0    ┆ 2274.0    ┆ 2274.0    │
│          ┆ ND_PRCP_MM  ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ SMR      ┆ WB_WDI_NY_G ┆ _T  ┆ San Marino  ┆ … ┆ All age     ┆ -5.473684 ┆ 1.493905  ┆ -6.647911 │
│          ┆ DP_MKTP_KD_ ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆ ZG          ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ NZL      ┆ WB_WDI_NY_T ┆ _T  ┆ New Zealand ┆ … ┆ All age     ┆ 1.9830e10 ┆ 2.6453e10 ┆ 2.6428e10 │
│          ┆ AX_NIND_KN  ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ …        ┆ …           ┆ …   ┆ …           ┆ … ┆ …           ┆ …         ┆ …         ┆ …         │
│ OED      ┆ WB_WDI_IC_F ┆ _T  ┆ OECD        ┆ … ┆ All age     ┆ null      ┆ null      ┆ null      │
│          ┆ RM_BKWC_ZS  ┆     ┆ members     ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ BGD      ┆ WB_WDI_IC_F ┆ _T  ┆ Bangladesh  ┆ … ┆ All age     ┆ null      ┆ null      ┆ null      │
│          ┆ RM_LOTM_ZS  ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ SGP      ┆ WB_WDI_SH_S ┆ F   ┆ Singapore   ┆ … ┆ All age     ┆ null      ┆ null      ┆ null      │
│          ┆ TA_STNT_FE_ ┆     ┆             ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆ ZS          ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ OED      ┆ WB_WDI_IC_F ┆ _T  ┆ OECD        ┆ … ┆ All age     ┆ null      ┆ null      ┆ null      │
│          ┆ RM_BNKS_ZS  ┆     ┆ members     ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
│ GBR      ┆ WB_WDI_SH_S ┆ F   ┆ United      ┆ … ┆ All age     ┆ null      ┆ null      ┆ null      │
│          ┆ TA_AIRP_FE_ ┆     ┆ Kingdom     ┆   ┆ ranges or   ┆           ┆           ┆           │
│          ┆ P5          ┆     ┆             ┆   ┆ no          ┆           ┆           ┆           │
│          ┆             ┆     ┆             ┆   ┆ breakdown…  ┆           ┆           ┆           │
└──────────┴─────────────┴─────┴─────────────┴───┴─────────────┴───────────┴───────────┴───────────┘

In [8]:
widef_pl["AGE_LABEL"].unique()

shape: (22,)
Series: 'AGE_LABEL' [str]
[
	"40 to 44 years old"
	"30 to 34 years old"
	"80 years old and over"
	"20 to 24 years old"
	"35 to 39 years old"
	…
	"70 to 74 years old"
	"All age ranges or no breakdown…
	"50 to 54 years old"
	"5 to 9 years old"
	"55 to 59 years old"
]

In [25]:
import numpy as np
import polars as pl

working_age = [
    "WB_WDI_SP_POP_2024",
    "WB_WDI_SP_POP_2529",
    "WB_WDI_SP_POP_3034",
    "WB_WDI_SP_POP_3539",
    "WB_WDI_SP_POP_4044",
    "WB_WDI_SP_POP_4549",
    "WB_WDI_SP_POP_5054",
    "WB_WDI_SP_POP_5559",
    "WB_WDI_SP_POP_6064"
]

retirement_age = [
    "WB_WDI_SP_POP_65UP",
    "WB_WDI_SP_POP_6569",
    "WB_WDI_SP_POP_7074",
    "WB_WDI_SP_POP_7579",
    "WB_WDI_SP_POP_80UP"
]

widef_pl = widef_pl.with_columns(
    pl.when(pl.col("INDICATOR").str.contains("SP_POP_2024|SP_POP_2529|SP_POP_3034|SP_POP_3539|SP_POP_4044|SP_POP_4549|SP_POP_5054|SP_POP_5559|SP_POP_6064"))
    .then(pl.lit("working_age"))
    .when(pl.col("INDICATOR").str.contains("SP_POP_65UP|SP_POP_6569|SP_POP_7074|SP_POP_7579|SP_POP_80UP"))
    .then(pl.lit("retirement_age"))
    .otherwise(pl.lit("other"))
    .alias("AGE_GROUP")
)

print(widef_pl.filter(pl.col("AGE_GROUP") == "working_age"))
print(widef_pl.filter(pl.col("AGE_GROUP") == "retirement_age"))

shape: (4_770, 11)
┌──────────┬────────────────────┬─────┬────────┬───┬───────────┬──────────┬──────────┬─────────────┐
│ REF_AREA ┆ INDICATOR          ┆ SEX ┆ AGE    ┆ … ┆ AGE_LABEL ┆ 2010     ┆ 2018     ┆ AGE_GROUP   │
│ ---      ┆ ---                ┆ --- ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---         │
│ str      ┆ str                ┆ str ┆ str    ┆   ┆ str       ┆ f64      ┆ f64      ┆ str         │
╞══════════╪════════════════════╪═════╪════════╪═══╪═══════════╪══════════╪══════════╪═════════════╡
│ FRO      ┆ WB_WDI_SP_POP_2529 ┆ F   ┆ Y25T29 ┆ … ┆ 25 to 29  ┆ 4.619012 ┆ 5.397687 ┆ working_age │
│          ┆ _FE_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ LTU      ┆ WB_WDI_SP_POP_4549 ┆ M   ┆ Y45T49 ┆ … ┆ 45 to 49  ┆ 7.999132 ┆ 7.448568 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ BEL      ┆ WB_WDI_SP_POP_5054 ┆ M   ┆ Y50T54 ┆ … ┆ 50 to 54  ┆ 7.232739 ┆ 7.256239 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ BIH      ┆ WB_WDI_SP_POP_4549 ┆ F   ┆ Y45T49 ┆ … ┆ 45 to 49  ┆ 7.431352 ┆ 6.273706 ┆ working_age │
│          ┆ _FE_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ IND      ┆ WB_WDI_SP_POP_6064 ┆ M   ┆ Y60T64 ┆ … ┆ 60 to 64  ┆ 2.510203 ┆ 3.275494 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ …        ┆ …                  ┆ …   ┆ …      ┆ … ┆ …         ┆ …        ┆ …        ┆ …           │
│ FCS      ┆ WB_WDI_SP_POP_3034 ┆ F   ┆ Y30T34 ┆ … ┆ 30 to 34  ┆ 6.533288 ┆ 6.566336 ┆ working_age │
│          ┆ _FE_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ SAS      ┆ WB_WDI_SP_POP_2024 ┆ M   ┆ Y20T24 ┆ … ┆ 20 to 24  ┆ 9.451445 ┆ 9.251169 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ HIC      ┆ WB_WDI_SP_POP_4549 ┆ M   ┆ Y45T49 ┆ … ┆ 45 to 49  ┆ 7.410345 ┆ 7.086253 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ COL      ┆ WB_WDI_SP_POP_2024 ┆ M   ┆ Y20T24 ┆ … ┆ 20 to 24  ┆ 8.983095 ┆ 9.114774 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
│ FIN      ┆ WB_WDI_SP_POP_5559 ┆ M   ┆ Y55T59 ┆ … ┆ 55 to 59  ┆ 7.267521 ┆ 6.694983 ┆ working_age │
│          ┆ _MA_5Y             ┆     ┆        ┆   ┆ years old ┆          ┆          ┆             │
└──────────┴────────────────────┴─────┴────────┴───┴───────────┴──────────┴──────────┴─────────────┘
shape: (3_710, 11)
┌──────────┬──────────────┬─────┬────────┬───┬──────────────┬───────────┬───────────┬──────────────┐
│ REF_AREA ┆ INDICATOR    ┆ SEX ┆ AGE    ┆ … ┆ AGE_LABEL    ┆ 2010      ┆ 2018      ┆ AGE_GROUP    │
│ ---      ┆ ---          ┆ --- ┆ ---    ┆   ┆ ---          ┆ ---       ┆ ---       ┆ ---          │
│ str      ┆ str          ┆ str ┆ str    ┆   ┆ str          ┆ f64       ┆ f64       ┆ str          │
╞══════════╪══════════════╪═════╪════════╪═══╪══════════════╪═══════════╪═══════════╪══════════════╡
│ TSS      ┆ WB_WDI_SP_PO ┆ F   ┆ Y_GE65 ┆ … ┆ 65 years old ┆ 3.264992  ┆ 3.359498  ┆ retirement_a │
│          ┆ P_65UP_FE_ZS ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
│ DEU      ┆ WB_WDI_SP_PO ┆ F   ┆ Y_GE80 ┆ … ┆ 80 years old ┆ 6.84563   ┆ 7.849763  ┆ retirement_a │
│          ┆ P_80UP_FE_5Y ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
│ CPV      ┆ WB_WDI_SP_PO ┆ _T  ┆ Y_GE65 ┆ … ┆ 65 years old ┆ 25020.0   ┆ 28946.0   ┆ retirement_a │
│          ┆ P_65UP_TO    ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
│ PRT      ┆ WB_WDI_SP_PO ┆ F   ┆ Y75T79 ┆ … ┆ 75 to 79     ┆ 4.518764  ┆ 4.536679  ┆ retirement_a │
│          ┆ P_7579_FE_5Y ┆     ┆        ┆   ┆ years old    ┆           ┆           ┆ ge           │
│ USA      ┆ WB_WDI_SP_PO ┆ F   ┆ Y_GE65 ┆ … ┆ 65 years old ┆ 14.455295 ┆ 16.804587 ┆ retirement_a │
│          ┆ P_65UP_FE_ZS ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
│ …        ┆ …            ┆ …   ┆ …      ┆ … ┆ …            ┆ …         ┆ …         ┆ …            │
│ WLD      ┆ WB_WDI_SP_PO ┆ F   ┆ Y65T69 ┆ … ┆ 65 to 69     ┆ 2.659007  ┆ 3.440843  ┆ retirement_a │
│          ┆ P_6569_FE_5Y ┆     ┆        ┆   ┆ years old    ┆           ┆           ┆ ge           │
│ PRI      ┆ WB_WDI_SP_PO ┆ F   ┆ Y70T74 ┆ … ┆ 70 to 74     ┆ 3.858668  ┆ 5.442905  ┆ retirement_a │
│          ┆ P_7074_FE_5Y ┆     ┆        ┆   ┆ years old    ┆           ┆           ┆ ge           │
│ MYS      ┆ WB_WDI_SP_PO ┆ M   ┆ Y75T79 ┆ … ┆ 75 to 79     ┆ 0.744345  ┆ 0.926619  ┆ retirement_a │
│          ┆ P_7579_MA_5Y ┆     ┆        ┆   ┆ years old    ┆           ┆           ┆ ge           │
│ GBR      ┆ WB_WDI_SP_PO ┆ _T  ┆ Y_GE65 ┆ … ┆ 65 years old ┆ 16.338385 ┆ 18.25575  ┆ retirement_a │
│          ┆ P_65UP_TO_ZS ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
│ LCA      ┆ WB_WDI_SP_PO ┆ M   ┆ Y_GE65 ┆ … ┆ 65 years old ┆ 6.473393  ┆ 7.337911  ┆ retirement_a │
│          ┆ P_65UP_MA_ZS ┆     ┆        ┆   ┆ and over     ┆           ┆           ┆ ge           │
└──────────┴──────────────┴─────┴────────┴───┴──────────────┴───────────┴───────────┴──────────────┘

In [26]:
import polars as pl

countries_wb = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas, The","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo, Dem. Rep.","Congo, Rep.","Costa Rica","Cote d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt, Arab Rep.","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia, The","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran, Islamic Rep.","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea, Rep.","Korea, Dem. People's Rep.","Kuwait","Kyrgyz Republic","Lao PDR","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia, Fed. Sts.","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovak Republic","Slovenia","Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","St. Kitts and Nevis","St. Lucia","St. Vincent and the Grenadines","Sudan","Suriname","Sweden","Switzerland","Syrian Arab Republic","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela, RB","Vietnam","West Bank and Gaza","Yemen, Rep.","Zambia","Zimbabwe"]

countries_wb_extended = countries_wb + [
    "Kosovo",
    "Macao SAR, China",
    "Hong Kong SAR, China"
]

widef_pl = (
    widef_pl
    .with_columns(
        pl.when(pl.col("REF_AREA_LABEL").str.contains("rkiye"))
        .then(pl.lit("Turkey"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Ivoire"))
        .then(pl.lit("Cote d'Ivoire"))
        .when(pl.col("REF_AREA_LABEL").str.contains("Tome"))
        .then(pl.lit("Sao Tome and Principe"))
        .when(pl.col("REF_AREA_LABEL") == "Federal Republic of Somalia")
        .then(pl.lit("Somalia"))
        .otherwise(pl.col("REF_AREA_LABEL"))
        .alias("REF_AREA_LABEL")
    )
    .filter(pl.col("REF_AREA_LABEL").is_in(countries_wb_extended))
)

print(widef_pl["REF_AREA_LABEL"].n_unique())
print(widef_pl["REF_AREA_LABEL"].unique().sort().to_list())

196
['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']